## YAML Template.
---

#spring:
 # datasource:
  #  url: your-aws-instance-name.cilpbkfpr6xs.ap-south-1.rds.amazonaws.com/Your-DB-Name
   # username: your-instance-username
   # password: your-instance-password
  #jpa: 
   #   hibernate.ddl-auto: update
    #  generate-dll: true
     # show-sql: true
